[package]
name = "rarible-merkle-verify"
version = "0.0.1"
edition = "2021"

[dependencies]
anchor-lang = {version = "0.30.1"}
anchor-spl = {version = "0.30.1"}
solana-program = {version = "2.0.14"}

[features]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
